version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=banking_system
      - DB_HOST=db
      - DB_PORT=5432
      - NATS_URL=nats://nats:4222
    depends_on:
      - db
      - nats

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: banking_system
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nats:
    image: nats:2.9.4
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]

volumes:
  postgres_data:
